default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
  key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
  issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
  key_filepath: File.expand_path("~/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8"),
  in_house: false
)

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/calculator_app.ipa"
    )
  end
end
