default_platform(:ios)

platform :ios do
  lane :beta do
    api_key = app_store_connect_api_key(
  key_id: 8IV3FR4JWZ25,
  issuer_id: 69a6de7a-9fc3-47e3-e053-5b8c7c11a4d1,
  key_filepath: File.expand_path("~/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_API_KEY_ID']}.p8"),
  in_house: false
)

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/calculator_app.ipa"
    )
  end
end
